# Generated by Django 5.2.5 on 2025-09-02 20:27

import Agent.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CV', 'Curriculum Vitae'), ('LM', 'Lettre de Motivation')], max_length=2)),
                ('titre', models.CharField(max_length=255)),
                ('poste', models.CharField(max_length=255)),
                ('entreprise', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('contenu', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('template_utilise', models.CharField(default='default', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CVImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Agent.models.cv_image_path)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_image', to='Agent.document')),
            ],
        ),
        migrations.CreateModel(
            name='EtapeTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.IntegerField()),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=10)),
                ('details', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agent.document')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
