# Generated by Django 5.2.6 on 2025-09-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapetraitement',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etape_traitement_set', to='Agent.document'),
        ),
    ]
