# Generated by Django 5.2.6 on 2025-09-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0002_alter_etapetraitement_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='github_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=2),
        ),
        migrations.AddField(
            model_name='document',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
